[package]
name = "pkarr-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pkarr = "3.7.1"
tokio = { version = "1.0", features = ["rt"] }
lazy_static = "1.4"
hex = "0.4"
ed25519-dalek = "2.1.0"
